export const SET_DATE_RANGE = "SET_DATE_RANGE";
export const RESET_DATE_RANGE = "RESET_DATE_RANGE";
export const SET_TABLE_POSITION_PROPS = "SET_TABLE_POSITION_PROPS";
export const SET_TABLE_FILTERS = "SET_TABLE_FILTERS";
export const SET_REPORTS = "SET_REPORTS";
export const SET_ALL_APPS = "SET_ALL_APPS";
